level_multipliers:
  base: 1.0
  increment: 5.0

multiplier_tiers:
  TIER_1: 1.0
  TIER_2: 1.5
  TIER_2B: 2.5
  TIER_3: 3.0
  TIER_3B: 3.5
  TIER_4: 4.0
  TIER_4B: 4.5
  TIER_5: 5.0
  TIER_5B: 5.5
  TIER_6: 6.0

battle:
  CPU_LEVEL_DIFFERENCE_LOW: 4.0
  CPU_LEVEL_DIFFERENCE_HIGH: 200.0
  COIN_LOOT_MULTIPLIER: 4.0
  XP_MULTIPLIER_LOW: 2.0
  XP_MULTIPLIER_HIGH: 20.0

shop_prices:
  BRONZE_SHORT_SWORD: 12
  BRONZE_LONG_SWORD: 36
  IRON_SHORT_SWORD: 48
  IRON_LONG_SWORD: 192
  STEEL_SHORT_SWORD: 576
  STEEL_LONG_SWORD: 768
  DIAMOND_SHORT_SWORD: 2304
  DIAMOND_LONG_SWORD: 6912
  LEATHER_ARMOR: 46
  BRONZE_ARMOR: 230
  IRON_ARMOR: 1150
  STEEL_ARMOR: 5750
  DIAMOND_ARMOR: 28750
  COMMON_HEALING_POTION: 24
  UNCOMMON_HEALING_POTION: 48
  RARE_HEALING_POTION: 96
  LEGENDARY_HEALING_POTION: 192

inn:
  cost: 2
